image: node:12

cache:
  paths:
    - node_modules/
    - .yarn/

stages:
  - test
  - release

before_script:
  - node -v
  - npm -v
  - yarn -v
  - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  - yarn --pure-lockfile --cache-folder .yarn

build_and_test:
  stage: test
  script:
    - yarn run build
    - yarn run test:lint
    - yarn run doc
    # - yarn test
    # - yarn cov:check

publish_to_npm:
  stage: release
  only:
    - tags
  except:
    - branches
  script:
    - npm publish --verbose
