# Using https://github.com/marketplace/actions/deploy-to-github-pages
# See also https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
name: Deploy to Github pages

on:
  push:
    tags:
      - v*

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - run: yarn install --frozen-lockfile
    - run: yarn doc

    # start: temporary fix for broken link on nash.io/developers
    - run: mkdir docs/docs
    - run: echo "<a href='https://nash-io.github.io/api-client-typescript/'>Please visit https://nash-io.github.io/api-client-typescript/</a>" > docs/docs/index.html
    # end: temporary fix

    - run: touch docs/.nojekyll
    - name: Deploy docs 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
